### ISSUE TITLE
snowflake_flyway (Part 3)

### ISSUE THREAD

**Issue by vdhphuc** [kulmam92/snowflake_flyway#1]
Hi Yong,
Thank you for your blog.

In your blog https://community.snowflake.com/s/article/Snowflake-CI-CD-using-Flyway-and-Azure-DevOps-Pipeline-Part-3

[...Extracted from your blog]
Use the script below to create databases and a user for this demo:
`-- Create Databases
CREATE DATABASE FLYWAY_DEMO COMMENT = 'Azure DevOps deployment test';
CREATE DATABASE FLYWAY_DEMO_DEV COMMENT = 'Azure DevOps deployment test';
CREATE DATABASE FLYWAY_DEMO_QA COMMENT = 'Azure DevOps deployment test';

-- Create a Deploy User
-- I'm granting sysadmin role to make it simple but you'd better to create a role with necessary permissions.
create user devopsuser password='<mypassword>' default_role = sysadmin;`

[... Extracted fro your blog]

Would the databases be created within an Azure SQL Database or inside SnowFlake?

Thank you,
Philip

**Comment by kulmam92** [comment]
@vdhphuc You need to run that in snowflake.
